title: DeltaDatabase
description: A lightweight, encrypted-at-rest JSON database written in Go
baseurl: "/DeltaDatabase"
url: "https://deltarule.github.io"

remote_theme: just-the-docs/just-the-docs@v0.10.0

color_scheme: light

# Navigation
nav_enabled: true
nav_sort: order  # or 'case_insensitive'

# Search
search_enabled: true
search.heading_level: 2
search.previews: 3
search.preview_words_before: 5
search.preview_words_after: 10
search.tokenizer_separator: /[\s/]+/
search.rel_url: true
search.button: false

# Footer
footer_content: "DeltaDatabase is released under the <a href=\"https://github.com/DeltaRule/DeltaDatabase/blob/main/LICENSE\">DeltaDatabase Software License v1.0</a>."

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Code highlighting
highlighter: rouge
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  input: GFM
